### ISSUE TITLE
ToDo's for the for sparse pixels codes

### ISSUE THREAD

**Issue by jonwright** [FABLE-3DXRD/ImageD11#213]
- Currently there is a single threshold - it makes sense to have a lower threshold for higher angle data.
- Change the compression in the sparse files to be faster for IO
- Fix up the assemble_label code to recycle the previous files (h5py.ExternalLink or VDS)
- Use the new default filenames by default

**Comment by jonwright** [comment]
- [x] Currently there is a single threshold - it makes sense to have a lower threshold for higher angle data.. There is an option in assemble_label now to have a threshold image

- [x] DONE: Use the new default filenames by default 
- [x] clean up the notebooks to use default filenames (add experiment=ma1234, session=yymmdd, and get these from getcwd or silx or blissdata)

- [ ] Change the compression in the sparse files to be faster for IO

- [x] Fixing up the assemble_label code to recycle the previous files (h5py.ExternalLink or VDS), this means refactoring the segmentation to be writing into fewer files, or assembling as it goes.

- [x] make pks_table.tocolf and have this be comparable to reading of a columnfile

- [ ] move this issue into a projects thing?

**Comment by jonwright** [comment]
See if it can be integrated with the frelon peaksearch (e.g. allow that one to save sparse+labels and then call this one, and vice versa?)
